#!/usr/bin/with-contenv bash

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  set -x
fi

### Set Defaults
INSYNC1_DOWNLOAD=${DOWNLOAD:-"open-document"}
PROXY_MODE=${PROXY_MODE:-"NONE"}
BINARY_LOCATION=/usr/bin/insync-headless

echo '** [insync] Sleeping 10 seconds..'
sleep 10

### Set Proxy
if [ "$PROXY_MODE" = "NONE" ] || [ "$PROXY_MODE" = "none" ] || [ "$PROXY_MODE" = "system" ] || [ "$PROXY_MODE" = "SYSTEM" ] || [ "$PROXY_MODE" = "true" ] || [ "$PROXY_MODE" = "TRUE" ];  then
  PROXY_MODE=NONE
  /usr/bin/insync-headless set_proxy $PROXY_MODE
else
  echo "** [insync] Setting Proxy type to "$PROXY_MODE $PROXY_HOST" "$PROXY_PORT
  /usr/bin/insync-headless set_proxy $PROXY_MODE $PROXY_TYPE $PROXY_HOST $PROXY_PORT $PROXY_USER $PROXY_PASS
fi

### Check to see if accounts are unlinked
if $BINARY_LOCATION get_status | grep -q 'UNLINKED'; then
  echo '** [insync] Attempting to Authorize Accounts'
    NUM=`printenv | sort | grep '\INSYNC.*USERNAME' | wc -l`
    for (( i = 1; i <= $NUM; i++ ))
    do

        INSYNC_USERNAME=INSYNC${i}_USERNAME
        INSYNC_DOWNLOAD=INSYNC${i}_DOWNLOAD
        INSYNC_AUTH_CODE=INSYNC${i}_AUTH_CODE

        mkdir -p /data/${!INSYNC_USERNAME}
        echo '** [insync] Adding Account '${!INSYNC_USERNAME}
        /usr/bin/insync-headless add_account -a ${!INSYNC_AUTH_CODE} -p /data/${!INSYNC_USERNAME} -e ${!INSYNC_DOWNLOAD}
    done
fi
exec /bin/s6-pause -th
