version: '2'

services:
  insync-app:
    image: tiredofit/insync
    container_name: insync-app
    environment:
      - ZABBIX_HOSTNAME=insync-app

      - INSYNC1_USERNAME=user@gmail.com
      - INSYNC1_AUTH_CODE=12345
      - INSYNC_DOWNLOAD=open-document
    volumes:
      - ./data:/data
      - ./config:/root/.config/Insync
    restart: always
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
